---
- name: Create directory for burpsuite extensions
  ansible.builtin.file:
    path: "{{ burpsuite_extensions_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Download extension jar files
  ansible.builtin.get_url:
    url: "{{ extension.value.download_url }}"
    dest: "{{ burpsuite_extensions_dir }}/{{ extension.value.jar }}"
    checksum: "{{ extension.value.download_checksum }}"
    owner: root
    group: root
    mode: 0640
  loop: "{{ lookup('dict', burpsuite_extensions) }}"
  loop_control:
    loop_var: extension
  become: true
