---
- name: Configure burpsuite
  block:
    - name: Ensure config folder exists
      ansible.builtin.file:
        path: "{{ burpsuite_config_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add burpsuite configuration
      ansible.builtin.template:
        src: "{{ role_path }}/templates/UserConfig.json.j2"
        dest: "{{ burpsuite_config_dir }}/UserConfig{{ burpsuite_edition | capitalize }}.json"
        mode: 0700
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
