---
- name: Configure burpsuite java preferences
  block:
    - name: Ensure java preferences directory exists
      ansible.builtin.file:
        path: "{{ burpsuite_prefs_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Deploy burpsuite preferences
      ansible.builtin.template:
        src: "{{ role_path }}/templates/prefs.xml.j2"
        dest: "{{ burpsuite_prefs_file }}"
        mode: "0600"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
