---
- name: Converge
  hosts: all

  vars:
    ansible_user: root
    burpsuite_extensions_bapp:
      - name: "ParamMiner"
        bapp_uuid: "17d2949a985c4b7ca092728dba871943"
        bapp_serial_version: "33"
        loaded: true
      - name: "Content Type Converter"
        bapp_uuid: "db57ecbe2cb7446292a94aa6181c9278"
        bapp_serial_version: "4"
        loaded: true

    burpsuite_extensions_external:
      - name: "CSTC"
        download_url: "https://github.com/usdAG/cstc/releases/download/v1.3.4/CSTC-1.3.4-jar-with-dependencies.jar"
        loaded: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: pluggero.burpsuite
